#ifndef __AUTOCONF_LIB_PARAM_PARAM_LOCAL_H__
#define __AUTOCONF_LIB_PARAM_PARAM_LOCAL_H__

/* This file was automatically generated by mkparamdefs.pl. DO NOT EDIT */

/**
 * This structure describes a single service.
 */
struct loadparm_service 
{
	char *  szPath;
	const char **  szHostsallow;
	const char **  szHostsdeny;
	char *  fstype;
	const char **  ntvfs_handler;
	bool   bMSDfsRoot;
	bool   bBrowseable;
	bool   bRead_only;
	bool   bPrint_ok;
	bool   bMap_hidden;
	bool   bMap_archive;
	bool   bOpLocks;
	bool   bStrictSync;
	bool   bMap_system;
	int   iMaxConnections;
	int   iCSCPolicy;
	int   iCreate_mask;
	int   iCreate_force_mode;
	int   iDir_mask;
	int   iDir_force_mode;
	char *  szPreExec;
	char *  szPostExec;
	char *  szRootPreExec;
	char *  szRootPostExec;
	char *  szDontdescend;
	char *  szUsername;
	const char **  szInvalidUsers;
	const char **  szValidUsers;
	const char **  szAdminUsers;
	char *  szPrintcommand;
	char *  szLpqcommand;
	char *  szLprmcommand;
	char *  szLppausecommand;
	char *  szLpresumecommand;
	char *  szQueuepausecommand;
	char *  szQueueresumecommand;
	char *  szPrintername;
	char *  szPrintjobUsername;
	char *  szMagicScript;
	char *  szMagicOutput;
	char *  comment;
	char *  force_user;
	char *  force_group;
	const char **  readlist;
	const char **  writelist;
	const char **  printer_admin;
	const char **  szVfsObjects;
	char *  szMSDfsProxy;
	char *  volume;
	char *  szVetoFiles;
	char *  szHideFiles;
	char *  szVetoOplockFiles;
	char *  szAioWriteBehind;
	char *  szDfree;
	bool   autoloaded;
	bool   bPreexecClose;
	bool   bRootpreexecClose;
	int   iCaseSensitive;
	bool   bCasePreserve;
	bool   bShortCasePreserve;
	bool   bHideDotFiles;
	bool   bHideSpecialFiles;
	bool   bHideUnReadable;
	bool   bHideUnWriteableFiles;
	bool   bAccessBasedShareEnum;
	bool   bNo_set_dir;
	bool   bGuest_ok;
	bool   bGuest_only;
	bool   bAdministrative_share;
	bool   bPrintNotifyBackchannel;
	bool   bStoreDosAttributes;
	bool   bDmapiSupport;
	bool   bLocking;
	int   iStrictLocking;
	bool   bPosixLocking;
	bool   bKernelOplocks;
	bool   bLevel2OpLocks;
	bool   bKernelShareModes;
	bool   bOnlyUser;
	bool   bMangledNames;
	bool   bSymlinks;
	bool   bSyncAlways;
	bool   bStrictAllocate;
	bool   bDeleteReadonly;
	bool   bFakeOplocks;
	bool   bDeleteVetoFiles;
	bool   bDosFilemode;
	bool   bDosFiletimes;
	bool   bDosFiletimeResolution;
	bool   bFakeDirCreateTimes;
	bool   bBlockingLocks;
	bool   bInheritPerms;
	bool   bInheritACLS;
	bool   bInheritOwner;
	bool   bUseClientDriver;
	bool   bDefaultDevmode;
	bool   bForcePrintername;
	bool   bNTAclSupport;
	bool   bForceUnknownAclUser;
	bool   bEASupport;
	bool   bUseSendfile;
	bool   bProfileAcls;
	bool   bMap_acl_inherit;
	bool   bAfs_Share;
	bool   bAclCheckPermissions;
	bool   bAclGroupControl;
	bool   bAclMapFullControl;
	bool   bAclAllowExecuteAlways;
	int   iDefaultCase;
	int   iMinPrintSpace;
	int   iPrinting;
	int   iMaxReportedPrintJobs;
	int   iOplockContentionLimit;
	int   iWriteCacheSize;
	int   iBlock_size;
	int   iDfreeCacheTime;
	int   iallocation_roundup_size;
	int   iAioReadSize;
	int   iAioWriteSize;
	int   iMap_readonly;
	int   iDirectoryNameCacheSize;
	int   ismb_encrypt;
	char   magic_char;
	char *  szCupsOptions;
	bool   bChangeNotify;
	bool   bKernelChangeNotify;
	bool   bDurableHandles;
LOADPARM_EXTRA_LOCALS
};

#endif /* __AUTOCONF_LIB_PARAM_PARAM_LOCAL_H__ */

